file:
  directory: D:\download\greengramTDD

spring:
  datasource:
    driver-class-name:
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3_test
    username: root
    password: green502
  sql:
    init:
      mode: never #resources 아래에 있는 schema.sql (DB 생성 ,Table 생성 DDL)
      #, data.sql(데이터 insert DML) 파일을 프로젝트(테스트) 시작시 실행